### ISSUE TITLE
Not working on newest Nextcloud

### ISSUE THREAD

**Issue by DJIronic** [eneiluj/integration_mattermost#1]
Hello,

I installed the app to the latest nextcloud verion via cloning from github and settings permissions. I appeared in apps correctly for activation.

The issue is I can't see Mattermost in "connected accounts" both in user and admin settings. The dashboard card can be added to it, but it stays on infinite loading. 

On Events page (/settings/admin/logging) there is no issue, warning or Error from the App.

Do you have any idea whats going on and how to debug it?

Thank you!

**Comment by eneiluj** [comment]
You need to build the app when using the sources from the repo. If you know what you're doing:
```
npm ci
npm run dev
```
If not, just download the latest nightly or wait for a release :grin:.
